from skimage import data,transform
from matplotlib import pyplot as plt
img=data.camera()
plt.set_cmap(cmap='gray')
print(img.shape)
plt.figure(1)
plt.subplot(2,2,1)
plt.axis('off')
plt.title("original image")
plt.imshow(img)

tform=transform.SimilarityTransform(translation=(100,100))
img1=transform.warp(img,tform)
plt.figure(1)
plt.subplot(2,2,2)
plt.axis('off')
plt.title("image translation")
plt.imshow(img1)

img2=transform.rotate(img,30)
plt.figure(1)
plt.subplot(2,2,3)
plt.axis('off')
plt.title("rotate 30 degree")
plt.imshow(img2)

img3=transform.rotate(img,45)
plt.figure(1)
plt.subplot(2,2,4)
plt.axis('off')
plt.title("rotate 45 degree")
plt.imshow(img3)

img_small=transform.resize(img,(80,40))
plt.figure(2)
plt.subplot(1,4,1)
plt.axis('off')
plt.title("narrow")
plt.imshow(img_small)

img_large=transform.resize(img,(1024,1024))
plt.figure(2)
plt.subplot(1,4,2)
plt.title("amplification")
plt.axis('off')
plt.imshow(img_large)

img_scale1=transform.rescale(img,(0.3,0.3))
plt.figure(2)
plt.subplot(1,4,3)
plt.axis('off')
plt.title("equal scale reduction")
plt.imshow(img_scale1)

img_scale2=transform.rescale(img,(1.5,1.5))
plt.figure(2)
plt.subplot(1,4,4)
plt.axis('off')
plt.title("equal scale amplification")
plt.imshow(img_scale2)
i=transform
plt.show()